FROM node:alpine
WORKDIR '/app'
COPY package*.json ./
RUN npm i
COPY . .
RUN npm run build

FROM nginx
EXPOSE 3000
COPY ./nginx/default-k8s.conf /etc/nginx/conf.d/default.conf
COPY --from=0 /app/build /usr/share/nginx/html