AUTH0_DOMAIN=dev--3vto552.auth0.com
AUTH0_AUDIENCE=http://localhost:5000/api
TRANSMISSION_USERNAME=test
TRANSMISSION_PASSWORD=test
TRANSMISSION_PORT=443
TRANSMISSION_host=torrent.example.com
TRANSMISSION_SSL=true