language: generic
sudo: required

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json

after_success:
  - docker build -t mjrode/audible-client ./client
  - docker build -t mjrode/audible-api ./api
  - docker build -t mjrode/audible-nginx ./nginx

  # Login to Docker CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mjrode/audible-api
  - docker push mjrode/audible-client
  - docker push mjrode/audible-nginx
deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'audible'
  env: 'Audible-env'
  bucket_name: 'elasticbeanstalk-us-west-2-346528912368'
  bucket_path: 'audible'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
