version: "3.7"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app/backend
      - /backend/usr/src/app/node_modules

    ports:
      - "52000:5000"
    expose:
      - "5000"

    networks:
      - audible
    command: npm run start:dev

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /frontend/usr/src/app/node_modules
    networks:
      - audible
    depends_on:
      - backend
    ports:
      - "53000:3000"
    command: npm start
networks:
  audible:
    driver: bridge
